services:
  - type: web
    name: apc-wb-project
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
